### PR TITLE
Error handling on glottal and prosody

### PR DESCRIPTION
**Pull request by SamuelCahyawijaya**
Hi @jcvasquezc , I am handling some error on features extraction for glottal and prosody features, for now I just produce 0 value when the condition is not met:
1. Error handling for glottal features when len(GCI) < 2
2. Error handling on prosody features when `len(tilt)` and `len(mse)` equal 0

I am not really sure whether it is ok to just fill it with 0, please let me know if there is a more proper way to handle it.

### CODE REVIEW

**Comment by jcvasquezc** [comment]
Hi @SamuelCahyawijaya 
This could be a good initial solution to fix some specific bugs. 

For instance, for glottal features it is need that the speech frame has long voiced segments. This is why it is preferably to use it only for recordings of sustained vowels. If you have recordings with voiced segments with at least 100 ms length you can extract also the glottal features. In other conditions, there are not enough pitch periods to reconstruct the residual and glottal signals  to compute the features. Thus returning None or 0 could be a good indicator, but it could accompanied with a warning message about why the result appear.

For the prosody features this error occurs because a similar reason and its because there were not enough pitch periods detected in the speech utterance. You can return the 0 value but a warning indicating why the result is 0.

**Comment by SamuelCahyawijaya** [comment]
@jcvasquezc : Sure, I have added the warning messages. I also make another change in `articulation.py`, to prevent undefined variable when it calls the `dynamic2statict_artic` function.

Yeah, before I tried with longer audio and it works just fine, but then I need to work on chunked audio data which causes so many problems on the voice segment and pitch periods.

**Review by jcvasquezc — CHANGES_REQUESTED** [review]
do not change the requirements.txt file

**Comment by SamuelCahyawijaya** [comment]
Ah sorry, that was my mistake. I incorrectly commit unnecessary files before. I force push to undo the previous commit.

**Review by jcvasquezc — APPROVED** [review]

**Pull request merged**
